#!/usr/bin/osascript
on run argv
  tell application "System Events" to set UI elements enabled to true
  tell application "System Preferences"
    set current pane to pane id "com.apple.preferences.bluetooth"
    tell application "System Events"
      tell process "System Preferences"
        if value of checkbox 2 of window "Bluetooth" is 0 then
          if value of checkbox 0 of window "Bluetooth" is 0 then
            click checkbox 0 of window "Bluetooth"
          end if
          click checkbox 2 of window "Bluetooth"
        else
          if value of checkbox 0 of window "Bluetooth" is 1 then
            click checkbox 0 of window "Bluetooth"
          end if
          click checkbox 2 of window "Bluetooth"
        end if
      end tell
    end tell
    quit
  end tell
end run