#!/usr/bin/osascript
on run argv
  tell application "System Preferences"
    set current pane to pane id "com.apple.preferences.bluetooth"
    tell application "System Events"
      tell process "System Preferences"
        tell window "Bluetooth"
          tell button 6
            click
          end tell
          tell checkbox 0
            click
          end tell
        end tell
      end tell
    end tell
    quit
  end tell
end run