#!/usr/bin/osascript
on run argv
  set this_URL to item 1 of argv
  if (count of argv) > 1 then
    set background to item 2 of argv = "--background"
  else
    set background to false
  end if
  set previouslyActiveApp to path to frontmost application as text
  if previouslyActiveApp contains "Tweetbot.app" then
    set background to true
  end if
  if previouslyActiveApp contains "Reeder.app" then
    set background to true
  end if
  if previouslyActiveApp contains "Pocket.app" then
    set background to true
  end if
  if previouslyActiveApp contains "Airmail.app" then
    set background to true
  end if
  if previouslyActiveApp contains "Airmail Beta.app" then
    set background to true
  end if
  if application "Google Chrome" is not running then
    do shell script "open -a \"Google Chrome\" --args " & this_URL
  else
    tell application "Google Chrome"
      set theUrl to this_URL

      if (count every window) = 0 then
        make new window
      end if

      set existingIndex to -1
      set existingTab to null
      set emptyIndex to -1
      set emptyTab to null
      set theTabIndex to -1
      repeat with theWindow in every window
        set theTabIndex to 0
        repeat with theTab in every tab of theWindow
          set theTabIndex to theTabIndex + 1
          if theTab's URL = theUrl then
            set existingIndex to theTabIndex
            set existingTab to theTab
          end if
          if theTab's URL = "chrome://newtab/" then
            set emptyIndex to theTabIndex
            set emptyTab to theTab
          end if
        end repeat
      end repeat
      set theWindow to window 1

      if not existingIndex = -1 then
        set theWindow's active tab index to existingIndex
        tell existingTab to reload
      else
        if not emptyIndex = -1 then
          set theWindow's active tab index to emptyIndex
          set URL of emptyTab to theUrl
        else
          tell theWindow to make new tab with properties {URL:theUrl}
        end
      end if

      if not background then
        -- doesn't help the situation of existingIndex != -1
        tell application "System Events"
          set frontmost of process "Google Chrome" to true
        end tell
        activate
      end if
    end tell
  end if
end open location
