#!/usr/bin/osascript
on run argv
  set this_URL to item 1 of argv
  if (count of argv) > 1 then
    set background to item 2 of argv = "--background"
  else
    set background to false
  end if
  if application "Google Chrome" is not running then
    do shell script "open -a \"Google Chrome\" --args " & this_URL
  else
    tell application "Google Chrome"
      if not background then
        activate
      end

      set theUrl to this_URL

      if (count every window) = 0 then
        make new window
      end if

      set existingIndex to -1
      set existingTab to null
      set emptyIndex to -1
      set emptyTab to null
      set theTabIndex to -1
      repeat with theWindow in every window
        set theTabIndex to 0
        repeat with theTab in every tab of theWindow
          set theTabIndex to theTabIndex + 1
          if theTab's URL = theUrl then
            set existingIndex to theTabIndex
            set existingTab to theTab
          end if
          if theTab's URL = "chrome://newtab/" then
            set emptyIndex to theTabIndex
            set emptyTab to theTab
          end if
        end repeat
      end repeat

      if not existingIndex = -1 then
        tell existingTab to reload
        set theWindow's active tab index to existingIndex
        set index of theWindow to 1
      else
        if not emptyIndex = -1 then
          set URL of emptyTab to theUrl
          set theWindow's active tab index to emptyIndex
          set index of theWindow to 1
        else
          tell window 1 to make new tab with properties {URL:theUrl}
        end
      end if
    end tell
  end if
end open location
