#!/usr/bin/env python
import sys

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <bug number>"
  sys.exit(1)

issue_number = sys.argv[1].strip()
url = "https://issues.scala-lang.org/browse/SI-" + issue_number

import webbrowser
webbrowser.open(url)
