#!/usr/bin/env python
import sys

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <sha>"
  sys.exit(1)

sha = sys.argv[1].strip()
url = "https://github.com/scala/scala/commit/" + sha

import webbrowser
webbrowser.open(url)
