#!/usr/bin/env python
import os, sys, subprocess, webbrowser
from subprocess import call, check_output, Popen, PIPE

if len(sys.argv) == 1:
  call(["java", "-jar", "gitblit.jar"], cwd = "/usr/local/gitblit")
else:
  command = sys.argv[1]
  args = sys.argv[2:]

  script = Popen(["git", "rev-parse", "--show-toplevel"], stdout=PIPE)
  output = script.communicate()[0].strip()
  if script.returncode != 0:
    print output
    sys.exit(script.returncode)
  else:
    root = output
    head = check_output(["git", "rev-parse", "HEAD"]).strip()

  if command == "log":
    if len(args) == 0:
      url = "https://localhost:8443/log/" + os.path.basename(root).replace(" ", "%20")
      webbrowser.open(url)
    elif len(args) == 1:
      target = os.path.relpath(args[0], root)
      url = "https://localhost:8443/history/" + os.path.basename(root).replace(" ", "%20") + "/" + head + "/" + target.replace("/", "%2f")
      webbrowser.open(url)
    else:
      print "usage: " + sys.argv[0] + " log [target]"
      sys.exit(1)
  elif command == "blame":
    if len(args) == 1:
      target = os.path.relpath(args[0], root)
      url = "https://localhost:8443/blame/" + os.path.basename(root).replace(" ", "%20") + "/" + head + "/" + target.replace("/", "%2f")
      webbrowser.open(url)
    else:
      print "usage: " + sys.argv[0] + " blame <target>"
      sys.exit(1)
  else:
    print "unknown command: " + command
