#!/usr/bin/env python
import sys, os, filecmp, difflib
from subprocess import check_call

root = "/Users/xeno_by/Projects/pp-2012-simulation-grades"
backup_dir = "/Users/xeno_by/Projects/pp-2012-blueprint"
dirs = filter(lambda dir: dir != "!SOLUTION" and dir != ".git" and dir != "README.md", os.listdir(root))
blueprint_dir = root + "/!SOLUTION/src/main/scala/simulations"
interestings = ["Circuit.scala", "EpidemySimulator.scala"]
stubs = ["gui/EpidemyDisplay.scala", "gui/Grid.scala", "Simulator.scala"]

def compare_files(file1, file2):
  return filecmp.cmp(file1, file2, shallow = False)

# for dir in dirs:
#   for interesting in interestings:
#     blueprint = blueprint_dir + "/" + interesting
#     interesting = dir + "/" + interesting
#     check_call(["git", "add", interesting])
#   check_call(["git", "commit", "-m", dir])

for dir in dirs:
  for stub in stubs:
    blueprint = blueprint_dir + "/" + stub
    backup = backup_dir + "/" + dir + "/" + stub
    stub = dir + "/" + stub
    check_call(["cp", backup, stub])