#!/usr/bin/env python
import sys, os
from subprocess import Popen, PIPE

if len(sys.argv) > 2:
  print "usage: " + sys.argv[0] + " [<branch-like>]"
  sys.exit(1)

script = Popen(["hack-branch"] + sys.argv[1:], stdout=PIPE)
output = script.communicate()[0][:-1]
if script.returncode != 0:
  print output
  sys.exit(script.returncode)

projects_root = os.path.expandvars("$HOME/Projects")
projects = filter(os.path.isdir, map(lambda prj: os.path.join(projects_root, prj), os.listdir(projects_root)))
hacks = filter(lambda prj: os.path.exists(os.path.join(prj, ".hack")), projects)
hacks = dict((open(os.path.join(prj, ".hack")).read().strip(), prj) for prj in hacks)
project = hacks.get(output)

if project:
  print project
  sys.exit(0)
else:
  sys.exit(1)