#!/usr/bin/env python
import sys, os, re
from subprocess import check_output

if len(sys.argv) > 2:
  print "usage: " + sys.argv[0] + " [<branch-like>]"
  sys.exit(1)

branch = sys.argv[1] if len(sys.argv) == 2 else None
dothack = os.path.expandvars("$HOME/.hack")
if not branch and os.path.exists(dothack): branch = open(dothack).read().strip()
if not branch:
  print "Create ~/.hack with a branchname to call " + sys.argv[0] + " without an argument"
  sys.exit(1)

if not ":" in branch:
  hardcoded = ["master", "2.10.x"]
  if not branch in hardcoded:
    prefix = "ticket" if re.match("^\d+$", branch) else "topic"
    branch = prefix + "/" + branch
  branch = "xeno-by:" + branch

print branch