#!/usr/bin/env python
import sys, os, re
from subprocess import check_output

if len(sys.argv) != 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

dothack = os.path.expandvars("$HOME/.hackproto")
branch = open(dothack).read()
print branch