#!/usr/bin/env python
import sys, os
from subprocess import Popen, PIPE

if len(sys.argv) > 2:
  print "usage: " + sys.argv[0] + " [<branch-like>]"
  sys.exit(1)

script = Popen(["hack-branch"] + sys.argv[1:], stdout=PIPE)
output = script.communicate()[0][:-1]
if script.returncode != 0:
  print output
  sys.exit(script.returncode)

homes = Popen(["hack-homes", "--dirs"], stdout=PIPE).communicate()[0].splitlines()
index = dict((open(os.path.join(home, ".hack")).read().strip(), home) for home in homes)
project = index.get(output)

if project:
  print project
  sys.exit(0)
else:
  sys.exit(1)