#!/usr/bin/env python
import sys, os

if len(sys.argv) > 2:
  print "usage: " + sys.argv[0] + " [<branch-like>]"
  sys.exit(1)

branch = sys.argv[1] if len(sys.argv) == 2 else None

print os.path.expandvars("$HOME/Projects/Kepler")