#!/usr/bin/env python
import sys, os
from subprocess import Popen, PIPE

if len(sys.argv) != 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

projects_root = os.path.expandvars("$HOME/Projects")
projects = filter(os.path.isdir, map(lambda prj: os.path.join(projects_root, prj), os.listdir(projects_root)))
hacks = filter(lambda prj: os.path.exists(os.path.join(prj, ".hack")), projects)

for hack in hacks:
  print hack
