#!/usr/bin/env python
import sys, os, re
from subprocess import Popen, PIPE

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " {--all|--dirs|--short-branches|--full-branches}"
  sys.exit(1)

flavor = sys.argv[1]

projects_root = os.path.expandvars("$HOME/Projects")
projects = filter(os.path.isdir, map(lambda prj: os.path.join(projects_root, prj), os.listdir(projects_root)))
hacks = filter(lambda prj: os.path.exists(os.path.join(prj, ".hack")), projects)
index = dict((open(os.path.join(home, ".hack")).read().strip(), home) for home in hacks)

for branch, dir in index.items():
  if flavor == "--all":
    print dir.ljust(60, " ") + " " + branch
  if flavor == "--dirs":
    print dir
  elif flavor == "--full-branches":
    print branch
  elif flavor == "--short-branches":
    m = re.match("^(.*?):(.*?/)?(?P<short>.*)$", branch)
    if m: print m.expand("\g<short>")
