#!/usr/bin/osascript
on run argv
  if application "Google Chrome" is not running then
    do shell script "open -a \"Google Chrome\""
    do shell script "sleep 0.5"
  end
  tell application "Google Chrome"
    set hadWindows to true
    if (count every window) = 0 then
      set hadWindows to false
      make new window
    end if
    set w to window 1
    tell w to make new tab with properties {URL:"chrome://extensions-frame/?id=nckgahadagoaajjgafhacjanaoiihapd"}
    do shell script "sleep 0.2"
    set t to w's active tab
    repeat while (loading of t)
    end repeat
    execute t javascript "var btn = document.evaluate('//*[@id=\"nckgahadagoaajjgafhacjanaoiihapd\"]/div/div[2]/div/label/input', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue; if (!!!btn.checked) btn.click()"
    do shell script "sleep 0.5"
    if (count w's tabs) > 0 then
      close t
    end
    if not hadWindows then
      close w
    end if
  end tell
end open location
