#!/usr/bin/env python
import os, json

prefs = json.load(open("/Users/xeno_by/Library/Application Support/Google/Chrome/Default/Preferences"))
hangouts_settings = prefs["extensions"]["settings"]["nckgahadagoaajjgafhacjanaoiihapd"]
print "0" if "disable_reasons" in hangouts_settings else "1"
