#!/usr/bin/env python
import sys, re

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <url-like>"
  sys.exit(1)

url = sys.argv[1]

if url.endswith("/console"): url = url[:-len("console")]
if url.endswith("/consoleText"): url = url[:-len("consoleText")]
if url.endswith("/consoleFull"): url = url[:-len("consoleText")]
if not url.endswith("/"): url = url + "/"
if not re.match("^https://scala-webapps.epfl.ch/jenkins/(view/(.+?)/)?job/(.+?)/(\d+)/$", url):
  print "Invalid url: " + url
  sys.exit(1)

print url