#!/usr/bin/env python
import subprocess, sys, re, urllib2, traceback, time, json
from subprocess import Popen, call, PIPE

if len(sys.argv) > 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

introspect = Popen(["hub-introspect"], stdout=PIPE)
lines = introspect.communicate()[0].splitlines()
if introspect.returncode != 0:
  print "".join(lines)
  sys.exit(introspect.returncode)

user, repo, branch, status = lines
if not status.startswith("no changes"):
  print status
  sys.exit(1)

if repo == "palladium" and branch == "palladium":
  jenkins_url = "https://scala-webapps.epfl.ch/jenkins/view/misc/job/palladium-nightly-main/buildWithParameters?publish=true"
elif repo == "paradise" and branch == "2.10.2":
  jenkins_url = "https://scala-webapps.epfl.ch/jenkins/view/misc/job/macro-paradise-nightly-2.10.2/build"
elif repo == "paradise" and branch == "2.10.3":
  jenkins_url = "https://scala-webapps.epfl.ch/jenkins/view/misc/job/macro-paradise-nightly-2.10.3/build"
elif repo == "paradise" and branch == "2.10.x":
  jenkins_url = "https://scala-webapps.epfl.ch/jenkins/view/misc/job/macro-paradise-nightly-2.10.x/build"
elif repo == "paradise" and branch == "2.11.0":
  jenkins_url = "https://scala-webapps.epfl.ch/jenkins/view/misc/job/macro-paradise-nightly-2.11.0/build"
elif repo == "paradise" and branch == "virt":
  jenkins_url = "https://scala-webapps.epfl.ch/jenkins/view/misc/job/macro-paradise-nightly-virt/build"
else:
  jenkins_url = "https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/buildWithParameters"
  jenkins_url += "?githubUsername=" + user + "&repository=" + repo
  jenkins_url += "&branch=" + branch
  jenkins_url += "&storeArtifacts=true"

import webbrowser
webbrowser.open(jenkins_url)