#!/usr/bin/env python
from subprocess import call
import os, sys, re, json, urllib2, traceback

if len(sys.argv) > 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

def growl(message):
  call(["growlnotify", "-n", "Jenkins", "-m", message])

with open("/Users/xeno_by/.jenkins_daemon", "r") as config:
  jobs = map(lambda job: job.strip(), config.readlines())

new_jobs = []
anything_new = False
for job in jobs:
  if job:
    try:
      data = urllib2.urlopen(job + "/api/json").read()
      data = json.loads(data)
      result = data["result"]
      if result:
        anything_new = True
        msg = result + ": " + job
        growl(msg)
        print msg
      else:
        new_jobs.append(job)
    except:
      _, value, _ = sys.exc_info()
      msg = job + ": " + str(value)
      # growl(msg)
      print msg
      new_jobs.append(job)

if not anything_new:
  print "Nothing new"

with open("/Users/xeno_by/.jenkins_daemon", "w") as config:
  config.writelines(map(lambda job: job + "\n", new_jobs))
