#!/usr/bin/env python
import sys, re, subprocess

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <job url>"
  sys.exit(1)

job_url = sys.argv[1]

if re.match("^\d+$", job_url): job_url = "https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/" + job_url + "/"
if job_url.endswith("/console"): job_url = job_url[:-len("console")]
if job_url.endswith("/consoleText"): job_url = job_url[:-len("consoleText")]
if not job_url.endswith("/"): job_url = job_url + "/"
if not re.match("^https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/(\d+)/$", job_url):
  print "Invalid url: " + job_url
  sys.exit(1)

with open("/Users/xeno_by/.jenkins_daemon", "r") as config:
  lines = map(lambda line: line.strip(), config.readlines())

found = False
for line in lines:
  if line == job_url:
    found = True
if found:
  print "Already tracking " + job_url
else:
  lines.append(job_url)
  print "Started tracking " + job_url

with open("/Users/xeno_by/.jenkins_daemon", "w") as config:
  config.writelines(map(lambda line: line + "\n", lines))
