#!/usr/bin/env python
import subprocess, sys, re, urllib2, traceback, time, json
from subprocess import Popen, call, PIPE

if len(sys.argv) > 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

introspect = Popen(["hub-introspect"], stdout=PIPE)
lines = introspect.communicate()[0].splitlines()
if introspect.returncode != 0:
  print "".join(lines)
  sys.exit(introspect.returncode)

user, repo, branch, status = lines
if not status.startswith("no changes"):
  print status
  sys.exit(1)

if branch == "paradise/macros":
  jenkins_url = "https://scala-webapps.epfl.ch/jenkins/view/misc/job/macro-paradise-nightly-main/build?delay=0sec"
else:
  jenkins_url = "https://scala-webapps.epfl.ch/jenkins/job/scala-checkin-manual/buildWithParameters"
  jenkins_url += "?githubUsername=" + user + "&repository=" + repo
  jenkins_url += "&branch=" + branch
  jenkins_url += "&storeArtifacts=true"

import webbrowser
webbrowser.open(jenkins_url)