#!/usr/bin/env python
from subprocess import call
import os, sys, re, json, urllib2, traceback, time

if len(sys.argv) != 3:
  print "usage: " + sys.argv[0] + " <job url> <status>"
  sys.exit(1)

status = sys.argv[2]
job = sys.argv[1]

msg = status + ": " + job
call(["growlnotify", "-n", "Jenkins", "-m", msg])
print msg

# if result == "FAILURE":
#   call(["partest-import", url])
