#!/usr/bin/env python
import sys, re, subprocess
from subprocess import call, Popen, PIPE

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <url-like>"
  sys.exit(1)

script = Popen(["jenkins-url", sys.argv[1]], stdout=PIPE)
output = script.communicate()[0][:-1]
if script.returncode != 0:
  print output
  sys.exit(script.returncode)

with open("/Users/xeno_by/.jenkins", "r") as config:
  lines = map(lambda line: line.strip(), config.readlines())

url = output
if url in lines:
  print "Already tracking " + url
else:
  lines.append(url)
  print "Started tracking " + url

with open("/Users/xeno_by/.jenkins", "w") as config:
  config.writelines(map(lambda line: line + "\n", lines))
