#!/usr/bin/env python
import os, sys, subprocess, urllib2, re
from subprocess import call, Popen, PIPE

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <url-like>"
  sys.exit(1)

script = Popen(["jenkins-url", sys.argv[1]], stdout=PIPE)
output = script.communicate()[0][:-1]
if script.returncode != 0:
  print output
  sys.exit(script.returncode)

try:
  log_url = output + "/consoleText"
  data = map(lambda line: line.strip(), urllib2.urlopen(log_url).readlines())
  failures = []
  for line in data:
    m1 = re.match(r"^\[partest\] testing: \[\.\.\.\](.*?)\s*\[FAILED\]\s*$", line)
    m2 = re.match(r"^\[partest\] !!\s+\d+ - (.*?) .*$", line) # master partest
    m = m1 or m2
    if m: # 2.10.x partest
      test = m.group(1)
      if not test.startswith("/"): test = "/" + test
      if not test.startswith("/files"): test = "/files" + test
      test = test[len("/files/"):]
      failures.append(test)
  for failure in failures:
    print failure
except:
  _, value, _ = sys.exc_info()
  print value
  sys.exit(1)