#!/usr/bin/env python
from subprocess import call
import os, sys, re, json, urllib2, traceback

def growl(message):
  call(["growlnotify", "-n", "Jenkins", "-m", message])

with open("/Users/xeno_by/.jenkins_daemon") as config: jobs = config.readlines()

new_jobs = []
anything_new = False
for job in jobs:
  job = job.strip()
  if job:
    try:
      data = urllib2.urlopen(job + "/api/json").read()
      data = json.loads(data)
      result = data["result"]
      if result:
        anything_new = True
        msg = result + ": " + job
        growl(msg)
        print msg
      else:
        new_jobs += job
    except:
      msg = job + ": " + traceback.format_exc()
      # growl(msg)
      print msg
      new_jobs += job

if not anything_new:
  print "Nothing new"

with open("/Users/xeno_by/.jenkins_daemon", "w") as config: config.writelines(new_jobs)
