#!/usr/bin/osascript
on run argv
  tell application "iTerm"
    make new terminal
    set the bounds of the first window to {620, 0, 1435, 618}
    tell the current terminal
      activate current session
      launch session "Default Session"
      delay 0.4
      tell the last session
        write text "cd " & item 1 of argv
      end tell
    end tell
  end tell
end run