#!/usr/bin/env python
import os, sys, subprocess
from subprocess import call

if len(sys.argv) > 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

def check_make_root(path):
  has_makefile = os.path.exists(os.path.join(path, "Makefile"))
  if has_makefile:
    print path
    sys.exit(0)

path = os.path.abspath(".")
check_make_root(path)

while path != os.path.dirname(path):
  path = os.path.dirname(path)
  check_make_root(path)
