#!/usr/bin/env bash
set -o errexit
set -o verbose

git remote update
git checkout master
git pull origin master
git push origin master
git branch -D paradise/macros
git checkout -b paradise/macros
git merge origin/topic/pre-typemacros

git cherry-pick a9a5e83e89 # org.scala-lang.macro-paradise
git cherry-pick d3998d1ffa # type macros beta v2
git cherry-pick 1dccde3329 # SI-6859 type macros no longer crash sbt
git cherry-pick a2761958d6 # SI-6830 constructor annotations are broken in macro paradise
git cherry-pick efd65a03cd # quasiquotes milestone 1
git cherry-pick 6688cda9ff # Various refactoring and bug fixes for quasiquotes
git cherry-pick 4811819eaa # Changes the way quasiquotes attaches positions to trees
