#!/usr/bin/env python
import os, sys, subprocess, urllib2, re, time

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <url-like>"
  sys.exit(1)

job_url = sys.argv[1]
script = subprocess.Popen(["jenkins-failures", job_url], stdout=subprocess.PIPE)
failures = script.communicate()[0].splitlines()
if script.returncode != 0:
  print "".join(failures)
  sys.exit(script.returncode)

root = subprocess.Popen(["scala-root"], stdout=subprocess.PIPE).communicate()[0][:-1]
config_name = root + "/.partest"

tests = []
if os.path.exists(config_name):
  with open(config_name, "r") as config:
    tests = map(lambda test: test.strip(), config.readlines())
def comment_out(test):
  return "# " + test if test.strip() else test
tests = map(comment_out, tests)
if len(tests): tests = tests + [""]
tests += ["# imported from " + job_url]
tests += ["# timestamp: " + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())]
tests += failures

with open(config_name, "w") as config:
  config.writelines(map(lambda test: test + "\n", tests))
