#!/usr/bin/env python
import os, sys, subprocess, re

if len(sys.argv) != 3:
  print "usage: " + sys.argv[0] + " {--view|--edit} <fuzzy name or index in .partest>"
  sys.exit(1)

action = sys.argv[1]
view = action == "--view"
edit = not view
fuzzy = sys.argv[2]

def process(filename):
  if edit:
    subprocess.call(["subl", filename])
  else:
    print "=================="
    print filename
    print "=================="
    with open(filename, "r") as f: print f.read().strip()

script = subprocess.Popen(["partest-lookup", fuzzy], stdout=subprocess.PIPE)
output = script.communicate()[0][:-1]
if script.returncode != 0:
  print output
  sys.exit(script.returncode)

root = subprocess.Popen(["scala-root"], stdout=subprocess.PIPE).communicate()[0][:-1]
test = root + "/test/" + output
base, ext = os.path.splitext(test)

if os.path.exists(base): # dir
  for filename in os.listdir(base):
    process(os.path.join(base, filename))
elif os.path.exists(base + ".scala"):
  process(base + ".scala")
