#!/usr/bin/env python
import os, sys, subprocess, re

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <fuzzy name or index in .partest>"
  sys.exit(1)

script = subprocess.Popen(["partest-lookup", sys.argv[1]], stdout=subprocess.PIPE)
output = script.communicate()[0][:-1]
if script.returncode != 0:
  print output
  sys.exit(script.returncode)

root = subprocess.Popen(["scala-root"], stdout=subprocess.PIPE).communicate()[0][:-1]
test = root + "/test/" + output
base, ext = os.path.splitext(test)
flavor = os.path.basename(os.path.dirname(base))
checkfile = base + ".check"
logfile = base + "-" + flavor + ".log"
subprocess.call(["diffmerge", logfile, checkfile])