#!/usr/bin/env python
import os, sys, subprocess

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " {--view|--view-with-numbers|--edit}"
  sys.exit(1)

action = sys.argv[1]
view = action == "--view" or action == "--view-with-numbers"
numbers = action == "--view-with-numbers"

if view:
  root = subprocess.Popen(["scala-root"], stdout=subprocess.PIPE).communicate()[0][:-1]
  dotpartest = root + "/.partest"
  if os.path.exists(dotpartest):
    with open(dotpartest, "r") as config:
      tests = map(lambda test: test.strip(), config.readlines())
      tests = filter(lambda test: test and not test.startswith("#"), tests)
      def figure_out(test):
        if test.startswith("/"): test = test[1:]
        return test
      tests = map(figure_out, tests)
      for idx, test in enumerate(tests):
        msg = test
        if numbers: msg = "\033[31;1m!!\033[0m " + str(idx + 1).rjust(len(str(len(tests)))) + " - " + msg.ljust(42) + "[test failed]"
        print msg
else:
  root = subprocess.Popen(["scala-root"], stdout=subprocess.PIPE).communicate()[0][:-1]
  dotpartest = root + "/.partest"
  subprocess.call(["subl", dotpartest])