#!/usr/bin/env python
import sys

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <pull request number>"
  sys.exit(1)

pull_number = sys.argv[1].strip()
url = "https://github.com/scala/scala/pull/" + pull_number

import webbrowser
webbrowser.open(url)
