#!/usr/bin/env python
import os, sys, re, json, urllib2
from subprocess import Popen, PIPE

if len(sys.argv) > 2:
  print "usage: " + sys.argv[0] + " [<target branch>]"
  print "if the target branch is not specified"
  print "the script will try to load it from ~/.pullrequest"
  sys.exit(1)
target_branch = sys.argv[1] if len(sys.argv) == 2 else None

introspect = Popen(["hub-introspect"], stdout=PIPE)
lines = introspect.communicate()[0].splitlines()
if introspect.returncode != 0:
  print "".join(lines)
  sys.exit(introspect.returncode)

user, repo, branch, status = lines
if status != "no changes":
  print status
  sys.exit(1)

try:
  with open(os.path.expandvars("$HOME/.pullrequest"), "r") as f:
    config = json.load(f)
except Exception as e:
  config = []
target_branch = target_branch or config.get(user + ":" + repo)

data = urllib2.urlopen("https://api.github.com/repos/scala/scala/pulls").read()
pr = [pr for pr in json.loads(data) if pr["head"]["label"] == user + ":" + branch]
if pr:
  url = pr[0]["html_url"]
else:
  url = "https://github.com/" + user + "/" + repo + "/pull/new/"
  if target_branch: url += target_branch + "..."
  url += branch

import webbrowser
webbrowser.open(url)
