#!/usr/bin/env bash

reeder_running=$(ps aux | grep Reeder | grep -v grep)
if [[ -n $reeder_running ]]; then
  open -a /Applications/Reeder.app
else
  open -a /Applications/Reeder.app
  sleep 0.5
  reeder-focus-unread
fi
