#!/usr/bin/env python
import os, sys, shutil, subprocess
from subprocess import check_output

if len(sys.argv) > 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

root = check_output(["scala-root"]).strip()
if os.path.abspath(".") == root:
  print "rm-classfiles: refusing to work at Scala root"
  sys.exit(1)

def rm_classfiles(root):
  for _, subdirs, files in os.walk(root):
    for file in files:
      if file.endswith(".class") or file.endswith(".js") or file.endswith(".html"):
        os.unlink(os.path.join(root, file))
    for dir in subdirs:
      if dir == "lib" or dir == "index":
        shutil.rmtree(os.path.join(root, dir))
      rm_classfiles(os.path.join(root, dir))
  for _, subdirs, files in os.walk(root):
    if not subdirs and not files:
      os.rmdir(root)

rm_classfiles(os.path.abspath("."))