#!/usr/bin/env python#!/usr/bin/env python
import os, sys
from subprocess import check_call, check_output
from plistlib import readPlistFromString

s = check_output(["system_profiler", "SPDisplaysDataType", "-xml"]).strip()
plist = readPlistFromString(s)
discrete_videocard_active = "spdisplays_ndrvs" in plist[0]["_items"][1]
if discrete_videocard_active:
  check_call(["open", "-a", "/Applications/StarCraft II 2012 Beta/StarCraft II Beta.app"])
else:
  print "Activate the discrete videocard"
  sys.exit(1)
