#!/usr/bin/env python
import os, sys, glob
from subprocess import check_output, call, check_call, Popen, PIPE

program_name = os.path.basename(sys.argv[0])
scalac = program_name == "scalac-options"
repl = program_name == "scala-options"
fsc = program_name == "fsc-options"
scaladoc = program_name == "scaladoc-options"
scalap = program_name == "scalap-options"
partest = program_name == "partest-options"
options = sys.argv[1:]
git_root = Popen(["git", "rev-parse", "--show-toplevel"], stdout=PIPE, stderr=PIPE).communicate()[0][:-1]
is210 = not "jline-2.11.jar" in check_output(["scala-toolcp"])
is211 = not is210

def append_plugin(dir, name):
  jardir = os.path.join(os.path.abspath(dir), "plugin/target")
  jars = glob.glob(os.path.join(jardir, "*/*.jar"))
  jars.sort(key=lambda jar: os.path.getmtime(jar))
  if not "-Ystop-after:parser" in options: # this prevents a crash due to a bug in Global that I have no idea how to work around
    if jars:
      options.append("-Xplugin:" + jars[-1])
      print "-Xplugin-require:" + name
    else:
      print >> sys.stderr, "no " + name + " plugin found in " + jardir

def append_paradise_plugin(dir):
  append_plugin(dir, "macroparadise")
  global options
  options = map(lambda opt: opt if opt != "-Yquasiquote-debug" else "-P:macroparadise:-Yquasiquote-debug", options)

def append_spores_plugin(dir):
  append_plugin(dir, "spores")

# automatically enable the paradise plugin if in relevant directory
if not "fatal: " in git_root and os.path.abspath(git_root).startswith("/Users/xeno_by/Projects/Paradise"):
  append_paradise_plugin(git_root)

# automatically enable the spores plugin if in relevant directory
if not "fatal: " in git_root and os.path.abspath(git_root).startswith("/Users/xeno_by/Projects/Spores"):
  append_spores_plugin(git_root)

# automatically enable the virtual classes plugin if in relevant directory
if not "fatal: " in git_root and os.path.abspath(git_root).startswith("/Users/xeno_by/Projects/ScalaVC"):
  options.append("-Xplugin:" + git_root + "/build/quick/misc/scala-devel/plugins/virtualclasses.jar")
  print "-Xplugin-require:virtualclasses"

# if os.path.abspath(git_root).startswith("/Users/xeno_by/Projects/copy-untyped"):
#   append_paradise_plugin("/Users/xeno_by/Projects/Paradise211x")
# if os.path.abspath(git_root).startswith("/Users/xeno_by/Projects/Master"):
#   append_paradise_plugin("/Users/xeno_by/Projects/Paradise211x")
# if os.path.abspath(git_root).startswith("/Users/xeno_by/Projects/210x"):
#   append_paradise_plugin("/Users/xeno_by/Projects/Paradise210x")

# if os.path.abspath(git_root).startswith("/Users/xeno_by/Projects/Master"):
#   options.append("-cp")
#   options.append("/Users/xeno_by/Projects/scala-blitz/target/scala-2.11.0-SNAPSHOT/classes:.")

# if os.path.abspath(git_root).startswith("/Users/xeno_by/Projects/210x"):
#   options.append("-cp")
#   options.append("/Users/xeno_by/Projects/async/target/scala-2.10/scala-async_2.10-0.9.0-SNAPSHOT.jar:.")

if os.environ.get("SCALAC_OPTS"):
  # TODO: tokenize this correctly
  scalac_opts = os.environ["SCALAC_OPTS"].split(" ")
  options += scalac_opts

if repl and not any(option.endswith(".scala") for option in options) and not "fos-2013-grading" in git_root:
  options.append("-language:experimental.macros")

if not partest and not git_root.startswith("/Users/xeno_by/Projects/fos-"):
  options.append("-deprecation")
  options.append("-feature")

# TODO: doesn't look like this works well with partest
# if partest and not is210:
#   options.append("-optimize")

for opt in options:
  print opt
