#!/usr/bin/env python
import os, sys, subprocess
from subprocess import check_output

if len(sys.argv) > 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

root = check_output(["scala-root"]).strip()
tier = check_output(["scala-tier"]).strip()
if tier == "pack": classdir = "quick"
elif tier == "quick": classdir = "quick"
elif tier == "locker": classdir = "locker"
else: print "unknown tier: " + str(tier); sys.exit(1)
relative = "build/" + classdir + "/classes"
classes = os.path.join(root, relative)
asm = os.path.join(root, "build/asm/classes")
jline210 = os.path.join(root, "lib/jline.jar")
jline211 = os.path.expandvars("$HOME/.m2/repository/jline/jline/2.11/jline-2.11.jar")
forkjoin = os.path.join(root, "lib/forkjoin.jar")
library, reflect, compiler, scalap, repl, scaladoc = map(lambda name: os.path.join(classes, name), ["library", "reflect", "compiler", "scalap", "repl", "scaladoc"])
print ":".join([asm, jline210, jline211, forkjoin, library, reflect, compiler, scalap, repl, scaladoc])
