#!/usr/bin/env python
import os, sys, subprocess
from subprocess import Popen, PIPE

if len(sys.argv) > 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

if os.path.abspath(".").startswith("/Users/xeno_by/Projects/Paradise2103"):
  print "/Users/xeno_by/Projects/210x"
  sys.exit(0)

if os.path.abspath(".").startswith("/Users/xeno_by/Projects/Paradise210x"):
  print "/Users/xeno_by/Projects/210x"
  sys.exit(0)

if os.path.abspath(".").startswith("/Users/xeno_by/Projects/Paradise2110"):
  print "/Users/xeno_by/Projects/Master"
  sys.exit(0)

if os.path.abspath(".").startswith("/Users/xeno_by/Projects/Paradise2110M5"):
  print "/Users/xeno_by/Projects/Scala2100M5"
  sys.exit(0)

if os.path.abspath(".").startswith("/Users/xeno_by/Projects/Spores"):
  print "/Users/xeno_by/Projects/210x"
  sys.exit(0)

if os.path.abspath(".").startswith("/Users/xeno_by/Projects/ParadiseVirt"):
  print "/Users/xeno_by/Projects/Virt"
  sys.exit(0)

if os.path.abspath(".").startswith("/Users/xeno_by/Projects/eleven"):
  print "/Users/xeno_by/Projects/Palladium"
  sys.exit(0)

root = None
suffix = "/pull-binary-libs.sh"
current = os.path.abspath(".")
while current != "/":
  if os.path.exists(current + suffix):
    root = current
    break
  else:
    current = os.path.dirname(current)

root = root or subprocess.Popen(["hack-home"], stdout=subprocess.PIPE).communicate()[0][:-1]
if root.endswith("pack"): root = root + "/../.."
if root.endswith("pack/"): root = root + "../.."

print os.path.abspath(root)