#!/usr/bin/env python
import os, sys, subprocess
from subprocess import check_output

if len(sys.argv) > 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

root = check_output(["scala-root"]).strip()
tier = check_output(["scala-tier"]).strip()
relative = "build/" + tier + "/classes"
classes = os.path.join(root, relative)
asm = os.path.join(root, "build/asm/classes")
jline = os.path.join(root, "lib/jline.jar")
library, reflect, compiler, scalap = map(lambda name: os.path.join(classes, name), ["library", "reflect", "compiler", "scalap"])
print ":".join([asm, jline, library, reflect, compiler, scalap])
