#!/usr/bin/env python
import os, sys, subprocess
from subprocess import check_output

if len(sys.argv) > 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)

try:
  with open(os.path.expandvars("$HOME/.scala_tier"), "r") as f:
    tier = f.read()
except Exception as e:
  tier = "quick"

print tier
