#!/usr/bin/env bash

temp=$(ps axu | ack -v ack | ack skype)
skype_is_not_running=$?

if [[ $skype_is_not_running ]]; then
  open /Applications/Skype.app && sleep 10 && skype-menubar-updater 2>&1
else
  open /Applications/Skype.app
fi
