#!/usr/bin/env python
import sys, os, filecmp, difflib, shutil
from subprocess import check_call

root = "/Users/xeno_by/Projects/pp-2012-simulation-grades"
solution = root + "/!SOLUTION"
check_call(["bash", "-c", "echo 2 | sbt run"], cwd = solution)
