#!/usr/bin/env python
import sys
from subprocess import check_output

sys.argv = filter(lambda arg: not arg.startswith("-"), sys.argv)
if len(sys.argv) != 1:
  print "usage: " + sys.argv[0]
  sys.exit(1)


raw_output = check_output(["sudo", "defaults", "read", "/Volumes/Macintosh HD/.Spotlight-V100/VolumeConfiguration.plist", "Exclusions"])
for raw_exclusion in raw_output.strip().split("\n")[1:-1]:
  raw = raw_exclusion.strip()
  print raw[raw.find("\"") + 1 : raw.rfind("\"")]