#!/usr/bin/env bash
git status 1>/dev/null 2>&1
if [[ $? == 128 ]]; then
  hg status 1>/dev/null 2>&1
  if [[ $? == 255 ]]; then
    git status
  else
    cd "$(hg root)"
    stock-stree . &
  fi
else
  cd "$(git rev-parse --show-toplevel)"
  stock-stree . &
fi
