#!/usr/bin/env bash
#
root=$(git rev-parse --show-toplevel 2>/dev/null)
if [[ $? != 0 ]]; then
  echo "Not a git repository"
  exit 1
fi

cd "$root"
for file in $(git-ls-merge-conflicts); do
  subl -w "$file"
  git add "$file"
done