#!/usr/bin/env bash
cd "$(sbt-root)" && \
git remote update && \
git pull upstream "$(git rev-parse --abbrev-ref HEAD)" && \
git push origin "$(git rev-parse --abbrev-ref HEAD)" && \
gaika clean thermonuclear && \
gaika compile