#!/usr/bin/env python
import os, sys, re
from subprocess import call, check_output, STDOUT, CalledProcessError

if len(sys.argv) != 2:
  print "usage: " + sys.argv[0] + " <task>"
  sys.exit(1)

task = sys.argv[1]
if not "^" in task:
  task = task + " ^today"

try:
  check_output(["rtmcli", "add", task], stderr=STDOUT)
except CalledProcessError, err:
  message = err.output
  m = re.match("^.*FATAL -- : ERROR: .*?, Message: (.*?)[\.]?\s*\(.*", message)
  if m: message = str(m.groups()[0])
  m = re.match("^.*FATAL -- : (.*?)\(.*", message)
  if m: message = str(m.groups()[0])
  call(["terminal-notifier", "-title", "todo", "-message", message])
