#!/usr/bin/env bash
set -o verbose
cd /Users/xeno_by/Projects/Master
git branch -D ticket/5710
git push origin :ticket/5710
git branch -D ticket/5824
git push origin :ticket/5824
git branch -D ticket/6113
git push origin :ticket/6113
git branch -D ticket/6240
git push origin :ticket/6240
git branch -D ticket/6539
git push origin :ticket/6539
git branch -D ticket/6591
git push origin :ticket/6591
git branch -D ticket/6725
git push origin :ticket/6725
git branch -D ticket/6812
git push origin :ticket/6812
git branch -D ticket/6937
git push origin :ticket/6937
git branch -D ticket/6989
git push origin :ticket/6989
git branch -D ticket/7008
git push origin :ticket/7008
git branch -D ticket/7046
git push origin :ticket/7046
git branch -D ticket/7064
git push origin :ticket/7064
git branch -D ticket/7190
git push origin :ticket/7190
git branch -D ticket/7235
git push origin :ticket/7235
git branch -D ticket/7240
git push origin :ticket/7240
git branch -D topic/7112-followup-2101
git push origin :topic/7112-followup-2101
git branch -D topic/7112-followup-210x
git push origin :topic/7112-followup-210x
git branch -D topic/macro-trace
git push origin :topic/macro-trace
git branch -D topic/resetattrs-this
git push origin :topic/resetattrs-this
git branch -D topic/shannon-entropy
git push origin :topic/shannon-entropy
git branch -D topic/silence
git push origin :topic/silence
git branch -D topic/silence-the-log
git push origin :topic/silence-the-log
git remote update
git remote prune origin
cd -
hack -scalamacros:ticket/6725 --batch --force # merged
hack -scalamacros:topic/7047-master --batch --force # merged
hack -scalamacros:ticket/7190 --batch --force # merged
hack -scalamacros:ticket/7235 --batch --force # merged
hack -scalamacros:ticket/7240 --batch --force # merged
hack -scalamacros:topic/macro-trace --batch --force # merged
hack -scalamacros:topic/resetattrs-this --batch --force # merged
hack -scalamacros:topic/shannon-entropy --batch --force # merged
hack -scalamacros:topic/silence-the-log --batch --force # merged
hack -scalamacros:topic/snippet00 --batch --force # snippet
hack -scalamacros:topic/snippet01 --batch --force # snippet
hack -scalamacros:topic/splice-error-message --batch --force # merged
hack -scalamacros:pullrequest/paradise --batch --force # merged
