#!/usr/bin/env bash
set -o verbose
cd /Users/xeno_by/Projects/Master
git branch -D ticket/6638
git push origin :ticket/6638
git branch -D topic/annotation-error
git push origin :topic/annotation-error
git branch -D topic/auto-duplicate-expansions
git push origin :topic/auto-duplicate-expansions
git branch -D topic/enclosures
git push origin :topic/enclosures
git branch -D topic/ident-attachments
git push origin :topic/ident-attachments
git branch -D topic/ident-deprecation-warnings
git push origin :topic/ident-deprecation-warnings
git branch -D topic/pre-typemacros
git push origin :topic/pre-typemacros
git branch -D topic/showrawpos
git push origin :topic/showrawpos
git remote update
git remote prune origin
cd -
