#!/usr/bin/env python
import sys, os, re, time
from subprocess import check_output, check_call, call

check_call(["git", "checkout", "master"])
check_call(["git", "push", "-u", "origin", "master"])

def postprocess(branch):
  branch = branch.strip()
  if "*" in branch: return None
  if "->" in branch: return None
  if branch.startswith("remotes/origin/"): return branch[len("remotes/origin/"):]
  return None
backup = check_output(["git", "branch", "-a"]).strip().split("\n")
backup = map(postprocess, backup)
backup = filter(lambda branch: branch != None, backup)
print "Branches to backup: " + str(backup)

for branch in backup: call(["git", "checkout", branch])
call(["git", "push", "--all"])
call(["git", "checkout", "master"])
